[package]
name = "daemon"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "watson-daemon"
path = "src/main.rs"

[dependencies]
common = { path = "../common" }
futures-util = "0.3.31"
serde_json = "1.0"
tokio = "1.48.0"
zbus = {version = "5.12.0", features = ["tokio"]}
